version: '3.7'
services:

  bit-mongo:
    restart: always
    image: mongo
    container_name: 'bit-mongo'
    environment: 
      - MONGO_INITDB_DATABASE=bit-db
      - MONGO_INITDB_ROOT_USERNAME=user1
      - MONGO_INITDB_ROOT_PASSWORD=p@Ss1
    ports:
      - "27017:27017"
    networks:
      - bitdashboard-network
    volumes:
      - "/home/ubuntu/bit-dashboard-api/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "/home/ubuntu/bit-dashboard-api/database/data:/data/db"
      # - "./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      # - "./database/data:/data/db"

  bit-dashboard-api:
    restart: always
    image: bit-dashboard-api
    build: .
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run serve
    links: 
      - bit-mongo
    depends_on: 
      - bit-mongo
    networks:
      - bitdashboard-network

  bit-dashboard-api-worker:
    restart: always
    image: bit-dashboard-api-worker
    build:
      context: .
      dockerfile: Dockerfile-worker
    expose:
      - "4001"
    ports:
      - "4001:4001"
    command: npm run serve:sch
    links: 
      - bit-mongo
      - bit-dashboard-api
    depends_on: 
      - bit-mongo
      - bit-dashboard-api
    networks:
      - bitdashboard-network

networks:
  bitdashboard-network:
    driver: bridge